services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '4000:3000'
    env_file:
      - ./apps/server/.env
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '4001:80'
    env_file:
      - ./apps/web/.env
    environment:
      - PORT=80
      - BACKEND_URL=http://server:3000
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
