services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    env_file:
      - ./apps/server/.env
    networks:
      - app-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '4001:80'
    env_file:
      - ./apps/web/.env
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
