[build]
  base = "apps/web/"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "apps/web/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200